version: '2'
services:

# Official PHP+Apache container
# https://hub.docker.com/_/php

  php-apache:
    container_name: php-apache
    image: php:7.1-apache
    restart: always
    ports:
      - 80:80
    expose:
      - 4688
    volumes:
      - ./www:/var/www/html 
      - ./apache-configs/mod_status.conf:/etc/apache2/mods-enabled/status.conf
      - ./apache-configs/ports.conf:/etc/apache2/ports.conf
    networks:
        - metrics

# Prometheus Apache Exporter
# Official GitHub Repo
# https://github.com/Lusitaniae/apache_exporter
# My own docker container at the DockerHub
# https://hub.docker.com/repository/docker/danifernandezs/prometheus-apache-exporter

  prom-exporter:
    container_name: apache-exporter
    image: danifernandezs/prometheus-apache-exporter:v0.8.0
    restart: always
    expose:
      - 9117
    command: --scrape_uri="http://php-apache:4688/apache-stats/?auto"
    networks:
      - metrics
      - prometheus

# Node Exporter Official container
# https://hub.docker.com/r/prom/node-exporter

  node-exporter:
    container_name: prometheus-node-exporter
    image: prom/node-exporter:v1.0.0
    restart: always
    expose:
      - 9100
    networks:
      - prometheus

# Prometheus Official container
# https://hub.docker.com/r/prom/prometheus

  prometheus:
    container_name: prometheus-server
    image: prom/prometheus:v2.19.0
    restart: always
    user: root
    expose:
      - 9090
    volumes:
      - ./prometheus/config:/prometheus
      - ./prometheus/data/prometheus:/data
    command:
      - '--config.file=/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/data'
    networks:
      - prometheus

# Grafana Official container
# https://hub.docker.com/r/grafana/grafana

  grafana:
    container_name: grafana
    image: grafana/grafana:7.0.3
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - prometheus


networks:
    metrics:
    prometheus:
